services:
  postgres:
    image: postgres:15-alpine
    container_name: cauldron_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cauldron_network

volumes:
  postgres_data:

networks:
  cauldron_network:
    driver: bridge
